Questions = [
"What's the french word for to climb",
"What's the french word for to go back (not at the place)",
"What's the french word for to leave/go out",
"What's the french word for to come",
"What's the french word for to go somewhere",
"What's the french word for to be born",
"What's the french word for to go down",
"What's the french word for to enter",
"What's the french word for to stay",
"What's the french word for to fall",
"What's the french word for to return",
"What's the french word for to arrive",
"What's the french word for to die",
"What's the french word for to leave",
]