Questions = [
"What is the past particple for avoir - to have",
"What is the past particple for boire - to drink",
"What is the past particple for pouvoir - to be able to",
"What is the past particple for savoir - to know(info)",
"What is the past particple for mettre - to put",
"What is the past particple for prendre - to take",
"What is the past particple for connaître - to know(person/place)",
"What is the past particple for voir - to see",
"What is the past particple for écrire - to write",
"What is the past particple for devoir - to have to",
"What is the past particple for vouloir - to want",
"What is the past particple for faire - to do/make",
"What is the past particple for lire - to read",
"What is the past particple for dormir - to sleep",
"What is the past particple for ouvrir - to open",
"What is the past particple for pleuvoir - to rain",
"What is the past particple for rire - to laugh",
"What is the past particple for être - to be",
]